### PR TITLE
Change transition for NewCampaingActivity, Adding Check Network, WIP …

### PR DESCRIPTION
**Pull request by AndreSand**
Change transition for NewCampaingActivity, Adding Check Network, WIP for Register Activity

### CODE REVIEW

**Comment by AndreSand** [comment]
@alberto-campos @dbykovsky 

Please Merge.

Thanks.
Andres

**Comment by dbykovsky** [comment]
Andres, I'm merging this PR. Please, next time please don't push two features together, where one of them is not finished or WIP. There is a rule of thumb when you are building software – build a little -> test a little -> push it out. Start over. 
In this particular example you should've pushed connectivity check feature first without WIP code on main master branch. 
@alberto-campos

**Comment by AndreSand** [comment]
Denis, I agree, since I can't do merge; Every time I just want to push all my latest code :)

**Comment by dbykovsky** [comment]
Ability to merge has nothing to do with pushing all code (complete and incomplete) at once.

Here is an example how to avoid that:

Imagine you are working on two features:
Feature One consist of two files: JavaFileOne.java and JavaFileTwo.java
Feature Two consist of one file: JavaFileThree.java

Now imagine that Feature One is complete and ready to be pushed and then merged. But, feature Two is still WIP

Just do git commit add avaFileOne.java JavaFileTwo.java NOT git commit add .

And then create a pull request only with Feature One. 

Once Feature two is complete. Push it to existing PR (pull request) if previous one was not merged yet OR create a new PR.

I hope that helsp

**Pull request merged**
