### PR TITLE
added user Profile Image, User is able to update ProfileImage and email

### PR DESCRIPTION
**Pull request by AndreSand**
added user Profile Image, User is able to update ProfileImage and email

### CODE REVIEW

**Comment by AndreSand** [comment]
@alberto-campos @dbykovskyy Hi Guys, How come I can do a merge?

**Comment by AndreSand** [comment]
@dbykovsky @alberto-campos Hi Guys, How come I can do a merge?

**Comment by AndreSand** [comment]
@dbykovsky @alberto-campos Hi Guys, How come I can't do a merge?

**Comment by AndreSand** [comment]
Second pull has the correct code. App working fine.

Please merge my pull request, so we all are sync with the latest code.

Thanks,
Andres

@dbykovsky @alberto-campos

**Comment by dbykovsky** [comment]
I was just merged.

**Comment by AndreSand** [comment]
cool thank you :)

**Pull request merged**
